import type { Updater } from '@tanstack/vue-table'
import { Ref } from 'vue'
import { type ClassValue, clsx } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export const EMPTY_IMAGE = new Image(1, 1)
EMPTY_IMAGE.src =
  'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=='

export function getColorFromString(
  name: string,
  brightnessAdjustment: number = 1.0,
): string {
  let hash = 0
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash)
  }

  let r = (hash & 0xff0000) >> 16
  let g = (hash & 0x00ff00) >> 8
  let b = hash & 0x0000ff

  // Convert to pastel by averaging with white
  r = Math.round((r + 255) / 2)
  g = Math.round((g + 255) / 2)
  b = Math.round((b + 255) / 2)

  // Apply brightness adjustment and clamp between 0-255
  r = Math.min(255, Math.max(0, Math.round(r * brightnessAdjustment)))
  g = Math.min(255, Math.max(0, Math.round(g * brightnessAdjustment)))
  b = Math.min(255, Math.max(0, Math.round(b * brightnessAdjustment)))

  // Combine RGB into a hex string
  return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, '0')}`
}

/**
 * Generated by ChatGPT 4 turbo inspiration
 * Helper function that handles updating state in Vue components
 * using the TanStack Table updater pattern.
 *
 * @param updaterOrValue - Either a new value or an updater function
 * @param ref - The Vue ref to update
 */
export function valueUpdater<T>(
  updaterOrValue: Updater<T> | T,
  ref: Ref<T>,
): void {
  if (typeof updaterOrValue === 'function') {
    // If updaterOrValue is a function, call it with the current value
    const updater = updaterOrValue as (old: T) => T
    ref.value = updater(ref.value)
  } else {
    // Otherwise, directly set the value
    ref.value = updaterOrValue
  }
}
