/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/buildings/': RouteRecordInfo<'/admin/buildings/', '/admin/buildings', Record<never, never>, Record<never, never>>,
    '/admin/buildings/[buildingId]/rooms/': RouteRecordInfo<'/admin/buildings/[buildingId]/rooms/', '/admin/buildings/:buildingId/rooms', { buildingId: ParamValue<true> }, { buildingId: ParamValue<false> }>,
    '/admin/buildings/[buildingId]/rooms/[roomId]': RouteRecordInfo<'/admin/buildings/[buildingId]/rooms/[roomId]', '/admin/buildings/:buildingId/rooms/:roomId', { buildingId: ParamValue<true>, roomId: ParamValue<true> }, { buildingId: ParamValue<false>, roomId: ParamValue<false> }>,
    '/admin/datatable-example': RouteRecordInfo<'/admin/datatable-example', '/admin/datatable-example', Record<never, never>, Record<never, never>>,
    '/admin/equipment/': RouteRecordInfo<'/admin/equipment/', '/admin/equipment', Record<never, never>, Record<never, never>>,
    '/admin/import': RouteRecordInfo<'/admin/import', '/admin/import', Record<never, never>, Record<never, never>>,
    '/admin/schemas': RouteRecordInfo<'/admin/schemas', '/admin/schemas', Record<never, never>, Record<never, never>>,
    '/admin/subjects': RouteRecordInfo<'/admin/subjects', '/admin/subjects', Record<never, never>, Record<never, never>>,
    '/requirements': RouteRecordInfo<'/requirements', '/requirements', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    '/timetable': RouteRecordInfo<'/timetable', '/timetable', Record<never, never>, Record<never, never>>,
    '/timetables/': RouteRecordInfo<'/timetables/', '/timetables', Record<never, never>, Record<never, never>>,
  }
}
